#!/bin/bash

# bootstrap - Script to resolve all dependencies that the application requires to run.
#

# Drop out if one of the commands fails
set -e

# Ensure we are working from the top of the project
cd "$(dirname "$0")/.."

# If Brewfile exists then make sure dependencies are all installed and up to date
if [[ -f "Brewfile" ]]
then
  command -v brew > /dev/null && {
    echo "Homebrew is installed"
  } || {
    echo "==> Installing Homebrew…"
    curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh | bash
  }

  brew bundle check > /dev/null 2>&1 && {
    echo "Homebrew dependencies are up to date"
  } || {
    echo "==> Installing Homebrew dependencies…"
    brew bundle
  }
fi

# If package.json file exists then ensure Node.js is setup and run `npm install`
if [[ -f "package.json" ]]
then
  echo "==> Installing nvm (node version manager)…"
  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash

  # Add the following so nvm can be used within this script
  export NVM_DIR="$HOME/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
  [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

  echo "==> Installing appropriate version of node…"
  nvm install --lts

  echo "==> Installing npm dependencies…"
  npm install
fi
