#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

cd "$(dirname "$0")/.."

if [ -f "Brewfile" ]; then
  echo "==> Installing Homebrew…"
  curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh | bash

  brew bundle check >/dev/null 2>&1  || {
    echo "==> Installing Homebrew dependencies…"
    brew bundle
  }
fi

if [ -f "package.json" ]; then
  echo "==> Installing nvm (node version manager)…"
  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash

  # Add the following so nvm can be used within this script
  export NVM_DIR="$HOME/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
  [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

  echo "==> Installing appropriate version of node…"
  nvm install --lts

  echo "==> Installing npm dependencies…"
  npm install
fi
