#!/bin/bash

# cibuild: Setup environment for CI to run tests.
#

# Drop out if one of the commands fails
set -e

# Ensure we are working from the top of the project
cd "$(dirname "$0")/.."

echo "CI build started at…"
date "+%H:%M:%S"

# Run tests.
script/test
