#!/bin/bash

# test: Run test suite for project. Optionally run an individual test(s).
#

# Drop out if one of the commands fails
set -e

# Ensure we are working from the top of the project
cd "$(dirname "$0")/.."

# Ensure everything is up to date before running the tests
script/update

echo "==> Running tests…"

# Check if arguments are passed allowing call to specific test(s).
# As an example this calls a simple script to check these shell scripts are valid.
if [[ -n $@ ]]
then
  ./check_scripts "$@"
else
  ./check_scripts
fi
